import dotenv from 'dotenv';
import { build } from 'esbuild';
import fs from 'fs';
import path from 'path';

// Load env from root
const envPath = path.resolve(__dirname, '../../.env');
const envConfig = dotenv.config({ path: envPath }).parsed || {};
const SERVER_URL = envConfig.SERVER_URL || process.env.SERVER_URL || 'http://localhost:3099';
const SELECTOR_ELEMENT = envConfig.SELECTOR_ELEMENT || process.env.SELECTOR_ELEMENT || '.submission-result-accepted';

console.log(`Building extension with SERVER_URL=${SERVER_URL}`);

// 1. Generate settings.ts
const settingsContent = `// This file is generated by build.ts
export const settings = {
  serverUrl: '${SERVER_URL}',
  selectorElement: '${SELECTOR_ELEMENT}',
};
`;
const settingsPath = path.resolve(__dirname, 'settings.ts');
fs.writeFileSync(settingsPath, settingsContent);
console.log('Generated src/settings.ts');

// 2. Generate manifest.json
const templatePath = path.resolve(__dirname, '../manifest.json.template');
let manifestContent = fs.readFileSync(templatePath, 'utf8');
manifestContent = manifestContent.replace(/\{\{SERVER_URL\}\}/g, SERVER_URL);
const manifestPath = path.resolve(__dirname, '../manifest.json');
fs.writeFileSync(manifestPath, manifestContent);
console.log('Generated manifest.json');

// 3. Bundle with esbuild
build({
  entryPoints: [path.resolve(__dirname, 'content.ts')],
  outfile: path.resolve(__dirname, '../dist/content.js'),
  bundle: true,
  platform: 'browser',
  target: ['chrome100'],
})
  .then(() => {
    console.log('Bundled dist/content.js');
  })
  .catch(() => process.exit(1));
